# Generated by Django 6.0.4 on 2026-05-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quizattempt_answerrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('easy', '易'), ('medium', '中'), ('hard', '難')], default='medium', max_length=10, verbose_name='難易度'),
        ),
    ]
